<?php

namespace App\Http\Requests;

class addBookRequest extends BooksRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => self::NAME,
            'author' => self::INTEGER,
            'year' => self::YEAR,
            'edition' => self::INTEGER
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
