<?php

namespace App\Http\Requests\api;

use Illuminate\Contracts\Validation\Validator;

class RegisterRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'username' => self::LOGIN . '|unique:users,username',
            'email' => self::EMAIL . '|unique:users,email',
            'password' => self::PASSWORD
        ];
    }

    public function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
